### ISSUE TITLE
UI: Input field for "code" flow parameter is displayed truncated

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect-design#734] opened 2023-04-06 18:30 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When deploying a flow with parameters that are displayed as "code-input" text fields, runtime default values are not shown completely but are truncated.

How it is currently displayed:
![image](https://user-images.githubusercontent.com/11021147/230464104-bcdcfe4f-1674-4e14-8f96-14c0d328772b.png)

How it should be displayed:
![image](https://user-images.githubusercontent.com/11021147/230464248-7728d6ca-3489-4320-bff6-745c3aa77cda.png)

Tested with Chrome and Firefox

### Reproduction

```python3
from prefect import flow
from pydantic import Json


@flow
def main(
    param: Json = '[{"a": 1}]'
) -> None:
    pass

if __name__ == "__main__":
    main()
```

### Versions

```Text
Version:             2.9.0
API version:         0.8.4
Python version:      3.8.15
Git commit:          69f57bd5
Built:               Thu, Mar 30, 2023 1:08 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

**Comment by zhen0** [comment] 2023-04-21 18:43
Transferring to prefect-design as I think the issue is in the p-code-input component

**Closed** 2023-11-07 09:38 UTC
Labels: bug, priority:medium
